import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import mainimg from "../assets/futurama_main.jpeg";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>futurama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Mainimg src={mainimg.src} />
      </main>
    </Container>
  );
};

const Container = styled.div`
  min-height: 100vh;
  background: #f14a16;
`;

const Mainimg = styled.img`
  display: block;
  width: 600px;
  margin: 100px auto;
`;

export default Home;
