import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>futurama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </Container>
  );
};

const Container = styled.div`
  min-height: 100vh;
  background: #35589a;
`;

export default Home;
